name: Publish Nuget

on: workflow_dispatch

jobs:
  build:

    env:
      PROJECT: './src/OrchardCore.Modules.Resume.csproj'
     
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT
      
    - name: Build
      run: dotnet build $PROJECT --no-restore

    - name: Publish
      run: dotnet nuget push **\*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
